# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:11
from __future__ import unicode_literals

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(validators=[apps.main.models.validate_date_after_today])),
                ('end_date', models.DateTimeField(validators=[apps.main.models.validate_date_after_start])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to='main.User')),
            ],
        ),
    ]
