# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
        ('courses', '0003_auto_20161024_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', to='login_registration.User'),
        ),
    ]
